-- MySQL Script generated by MySQL Workbench
-- Thu Dec  3 00:49:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Country` (
  `idCountry` INT NOT NULL,
  `Name` VARCHAR(70) NOT NULL,
  `Descr` VARCHAR(200) NULL,
  `Comments` VARCHAR(500) COLLATE 'DEFAULT' NOT NULL,
  PRIMARY KEY (`idCountry`),
  UNIQUE INDEX `IntCode_UNIQUE` (`Comments` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Area` (
  `idArea` INT NOT NULL,
  `Name` VARCHAR(70) NOT NULL,
  `Descr` VARCHAR(300) NOT NULL,
  `Comments` VARCHAR(500) NULL,
  `Country_idCountry` INT NOT NULL,
  PRIMARY KEY (`idArea`, `Country_idCountry`),
  INDEX `fk_Area_Country_idx` (`Country_idCountry` ASC) VISIBLE,
  CONSTRAINT `fk_Area_Country`
    FOREIGN KEY (`Country_idCountry`)
    REFERENCES `mydb`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`District`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`District` (
  `idDistrict` INT NOT NULL,
  `Name` VARCHAR(70) NOT NULL,
  `Descr` VARCHAR(45) NULL,
  `Comments` VARCHAR(500) NULL,
  `Area_idArea` INT NOT NULL,
  `Area_Country_idCountry` INT NOT NULL,
  PRIMARY KEY (`idDistrict`, `Area_idArea`, `Area_Country_idCountry`),
  INDEX `fk_District_Area1_idx` (`Area_idArea` ASC, `Area_Country_idCountry` ASC) VISIBLE,
  CONSTRAINT `fk_District_Area1`
    FOREIGN KEY (`Area_idArea` , `Area_Country_idCountry`)
    REFERENCES `mydb`.`Area` (`idArea` , `Country_idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `idCity` INT NOT NULL,
  `Name` VARCHAR(70) NOT NULL,
  `Descr` VARCHAR(300) NULL,
  `Index` VARCHAR(10) NOT NULL,
  `Comments` VARCHAR(500) NULL,
  `District_idDistrict` INT NOT NULL,
  `District_Area_idArea` INT NOT NULL,
  `District_Area_Country_idCountry` INT NOT NULL,
  PRIMARY KEY (`idCity`, `District_idDistrict`, `District_Area_idArea`, `District_Area_Country_idCountry`),
  UNIQUE INDEX `Index_UNIQUE` (`Index` ASC) VISIBLE,
  INDEX `fk_City_District1_idx` (`District_idDistrict` ASC, `District_Area_idArea` ASC, `District_Area_Country_idCountry` ASC) VISIBLE,
  CONSTRAINT `fk_City_District1`
    FOREIGN KEY (`District_idDistrict` , `District_Area_idArea` , `District_Area_Country_idCountry`)
    REFERENCES `mydb`.`District` (`idDistrict` , `Area_idArea` , `Area_Country_idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Country`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Country` (`idCountry`, `Name`, `Descr`, `Comments`) VALUES (1, 'Russia', 'Russian Federation', DEFAULT);
INSERT INTO `mydb`.`Country` (`idCountry`, `Name`, `Descr`, `Comments`) VALUES (2, 'Belarus', NULL, DEFAULT);

COMMIT;

